version: "3.7"

services:
  app:
    build:
      context: ./Docker/php/8.0
    container_name: yampi_test_app
    image: somosyampi/php:8.0
    init: true
    volumes:
        - .:/app:delegated
    networks:
        - yampi

  nginx:
    build:
      context: ./Docker/nginx
    image: somosyampi/http
    ports:
        - 8007:80
    volumes:
        - .:/app:delegated
    environment:
      FPM_HOST: app
    networks:
        - yampi
    depends_on:
        - app

  db:
    image: mariadb:10.2
    container_name: yampi_test_db
    volumes:
        - ./mysql/data:/var/lib/mysql:${VOLUME_ATR:-delegated}
    restart: always
    ports:
        - 3305:3305
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: yampi
    networks:
        - yampi

  #DB Panel
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8001:8080
    networks:
      - yampi

networks:
  yampi:
    name: yampi
